### ISSUE TITLE
Add draft ID to Proposal data submission

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#11]
### Expected behavior

It would be good to add the Draft's ID to the Proposal data when the Proposal is being created. It will be much easier to get the Draft's ID this way, rather than recreating it on the client.

NOTE: We make use of Draft types for some adapter types like Onboarding where a user cannot sponsor themselves.

### Actual behavior

There is not a way to get the Draft's hash unless you recreate it on the client, after fetching the Proposal(s).

### Steps to reproduce the behavior

N/A

**Comment by fforbeck** [comment]
it now returns this response:

- **uniqueId**: the erc712 hash of the Proposal message.
- **uniqueIdDraft**: the erc712 hash of the Draft. If the proposal does not have a draft, it gets generated either way because the draft content is contained in the proposal content. We dont have to use it, but if we do have a Draft, then its is available for lookups. So you don't need to generate it on the client side.

```json
{
  "uniqueId": "0xfaa09abe714291de6d3b5a6daa0330e5d4367188680b02cbc042243269fa050c",
  "uniqueIdDraft": "0x8a08d261151050b116587a14e54af9f3171727f8581aeb8f797a47499df59c6d"
}
```
