### ISSUE TITLE
Archive/Invalidate old Drafts which have a Proposal

### ISSUE THREAD

**Issue by jtrein** [openlawteam/snapshot-hub#8]
### Expected behavior

When requesting `draft` types from the new draft endpoints, if a `proposal` exists for the draft, it should not be returned. This is because it is no longer technically a Draft from the perspective of the API consumer. How do we do this in a clear and reliable way?

**Idea**

We can leverage the upcoming Snapshot API's new unique hash field (this will be used for the "linked" Moloch `bytes32 proposalId` - **we need to make GH issue for this**) for the `draft` and `proposal` types. On `POST /message` of a `proposal` type we could use this same hash to check if it includes a Draft's unique hash as part of the JSON.

If it does include the hash, and a Draft is found in the database, we can somehow mark the Draft as archived. Now when the Draft(s) are fetched on `GET /:space/drafts/...` we can use Postgres to filter-out the archived ones.

### Actual behavior

Today all Drafts will be fetched on the `erc712` branch, regardless if a `proposal` exists for the Draft, or not.

### Steps to reproduce the behavior

N/A

---

@adridadou

**Comment by fforbeck** [comment]
@jtrein this is ready.

if you generate a Draft you receive back a uniqueId, then you can use the uniqueId to query the API and retrieve the Draft details.

Then when you sponsor a Draft, you build a new Proposal message using all the data retrieved using the Draft uniqueId. There is one trick though, you need to use the timestamp from the draft in the proposal message, otherwise the ERC712 hashes will not match.

I have released a fix for snapshot-js-erc712 lib in which you can provide the timestamp as parameter: https://github.com/openlawteam/snapshot-js-erc712/blob/master/utils/snapshotHub.ts#L215

With that we ensure the hashes will always match if the other attributes are identical. Otherwise it would always generate a new timestamp for each new proposal, and we don't want that when we are sponsoring a draft.
